import { PERMISSIONS } from './permissions';
import { ROLES } from './roles';

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  [ROLES.STUDENT]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_ENROLLMENT_READ,
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.STUDENT_ACADEMIC_RECORD_READ,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.COURSE_READ,
    PERMISSIONS.COURSE_ENROLLMENT_READ,
    PERMISSIONS.COURSE_ALLOCATION_READ,
    PERMISSIONS.ASSESSMENT_READ,
    PERMISSIONS.ASSESSMENT_CREATE,
    PERMISSIONS.ASSESSMENT_UPDATE,
    PERMISSIONS.ASSESSMENT_DELETE,
    PERMISSIONS.STUDENT_ACADEMIC_RECORD_READ,
  ],
};
